# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cl <- function(x) {
    .Call(`_SD_cl`, x)
}

csample <- function(m, size, replace, prob = as.numeric( c())) {
    .Call(`_SD_csample`, m, size, replace, prob)
}

fsample <- function(v, size, replace, prob = as.numeric( c())) {
    .Call(`_SD_fsample`, v, size, replace, prob)
}

mSD <- function(Y, n, mu, ml, S) {
    .Call(`_SD_mSD`, Y, n, mu, ml, S)
}

Amat <- function(rho) {
    .Call(`_SD_Amat`, rho)
}

gen <- function(n, rho) {
    .Call(`_SD_gen`, n, rho)
}

cmb <- function(n) {
    .Call(`_SD_cmb`, n)
}

stl_nth_element <- function(x, n) {
    .Call(`_SD_stl_nth_element`, x, n)
}

gammasim <- function(n, x, mu, ml, S, B, rho) {
    .Call(`_SD_gammasim`, n, x, mu, ml, S, B, rho)
}

